### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#1]
Starting from scratch. 
Core idea is to build open sourced website that contains helpful tips for new developers in field of health and productivity. Body and Time management basically.

**Comment by lotfijb** [comment]
can you assign this to me please ?

**Comment by asdsyd** [comment]
@lotfijb You have been assigned this issue. All the best.

**Comment by asdsyd** [comment]
Don't forget to include 'Closes #IssueNumber' in your PR message.

**Comment by asdsyd** [comment]
@lotfijb Are you working this?

**Comment by ratneshgupta01** [comment]
@asdsyd please assign this issue to me, I will also add the steps to let people know how to contribute in this project

**Comment by niteshk700** [comment]
assign me plz

**Comment by himanshuj0007** [comment]
assign me please
