### ISSUE TITLE
[BUG] Figure out and Fix Explore button

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#16]
Explore button is supposed to redirect to explore.html file . It directs to raw code. It must render the code.

**Comment by asdsyd** [comment]
@ishaanbedi Would you like to work on this?

**Comment by sambitsargam** [comment]
PLEASE USE VERCEL FOR HOSTING

**Comment by asdsyd** [comment]
Alright, thanks.
