### ISSUE TITLE
Beautify Contact us page

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#19]
Use tailwind css and make it consistent with the theme of website.

**Comment by burhanharoon** [comment]
Please assign this to me. I can work on it!

**Comment by burhanharoon** [comment]
Can you share some details that you want to share on the contact us page? Like any contact details or any sort of information?

**Comment by asdsyd** [comment]
It could include 
- Name 
- Email
- Phone (optional)
- Message 
Submit

**Comment by burhanharoon** [comment]
Got it.

**Comment by burhanharoon** [comment]
@asdsyd I have completed it, please have a look! Cheers!

**Comment by asdsyd** [comment]
The contact page doesn't render the css. Please look into it.

**Comment by tanyaa-arora** [comment]
@asdsyd I'd like to work on the task. Kindly assign it to me

**Comment by asdsyd** [comment]
> @asdsyd I'd like to work on the task. Kindly assign it to me

Hey @tanyaa-arora . The css work is already done. You have to fix the rendering issue. Please include a screenshot after you are done.
Current status:
![Screenshot 2022-10-15 at 1 24 27 PM](https://user-images.githubusercontent.com/77977076/195975982-4b435914-6aae-43bc-ab11-ab7167b4b5a4.png)

**Comment by tanyaa-arora** [comment]
![image](https://user-images.githubusercontent.com/72658472/195976850-3f2a0b55-960d-464e-96cd-0ec301949e3e.png)
I've fixed the rendering issue on contact page

**Comment by tanyaa-arora** [comment]
@asdsyd I've resolved the issue, kindly look at it

**Comment by asdsyd** [comment]
That's great @tanyaa-arora . Thank you for contributing.
