### ISSUE TITLE
First steps!!

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#2]
Deploy a basic website for healthy developers.
Suggestions are always welcomed!!
Create issues - get assigned - PR - happy coding!!

**Comment by sumit-022** [comment]
What we have to do in this exactly?

**Comment by asdsyd** [comment]
We are planning to publish Healthy Developer's first version website. You can start by creating a basic HTML home page with title 'Healthy Developer'.

**Comment by sumit-022** [comment]
Okay so I can work on this. Can you assign it to me

**Comment by asdsyd** [comment]
@sumit-022 You have been assigned this issue. All the best.
