### ISSUE TITLE
Design About page for healthy-dev

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#23]
- [ ] Use tailwind css
- [ ] Include a screenshot of render
- [ ] Consistent design language
- [ ] Link PR to this issue using this text --> 'Closes #issueNumber'

Do it as per your liking find how about pages are ,take some inspiration. Dont forget to talk about this repo is open sourced and is intended to help early devs in health care and productivity.

**Comment by arjunchoudhury07** [comment]
Hey can you please assign this task to me.

**Comment by arjunchoudhury07** [comment]
Is is ok if I change the folder structure of the project as the Tailwind Docs suggests to keep all the files under src folder.
You can take a look in the Docs: https://tailwindcss.com/docs/installation

**Comment by asdsyd** [comment]
Yes you can but make sure other pages get the corrected href and work properly after the changes made.

**Comment by arjunchoudhury07** [comment]
Yeah sure...Thanks for the quick reply.

**Comment by asdsyd** [comment]
@arjunchoudhury07  Please copy first comment and tick the boxes (Open Source practice).Thanks for contributing 🚀

**Comment by asdsyd** [comment]
@arjunchoudhury07 You need to make sure after changes it is working correctly. If you want to test it push it on the 'testing' branch.
