### ISSUE TITLE
Move the FAQ file to respective folder.

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#29]

**Comment by srigundeti10** [comment]
@asdsyd  please assign me

**Comment by srigundeti10** [comment]
hey @asdsyd  can you be a bit more specific please
like on what exactly i need to do please

**Comment by asdsyd** [comment]
Move faq. Html to src pages
Faq . Css to src assets

**Comment by srigundeti10** [comment]
ok sure thanks

**Comment by srigundeti10** [comment]
done
