### ISSUE TITLE
I want to add footer to the files

### ISSUE THREAD

**Issue by guptakshitij2308** [asdsyd/Healthy-developer#44]
Respected Developer (@asdsyd ) ,Kindly assign this issue to me under hacktober fest.

**Comment by AnonymousSudh** [comment]
hey. I will add footer. 
can you explain what is files here or on which page I have to add footer??

**Comment by asdsyd** [comment]
@AnonymousSudh footer which has copyright on homepage .

**Comment by asdsyd** [comment]
This issue is already assigned lets wait for him.

**Comment by asdsyd** [comment]
@AnonymousSudh this is assigned to you as prev PRs were affecting other elements by other user.
