### ISSUE TITLE
[BUG] Fix the image not being displayed in readme

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#55]

**Comment by asdsyd** [comment]
![Screenshot 2022-10-20 at 3 07 06 PM](https://user-images.githubusercontent.com/77977076/196913424-0d5af5d5-a4e7-4245-8204-81fa3cf83422.png)

**Comment by Jyoti050402** [comment]
Hey, I would like to work on this issue.

**Comment by asdsyd** [comment]
@Jyoti050402 You have been assigned.
