### ISSUE TITLE
Add this to READme

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#59]
![Screenshot 2022-10-27 at 3 51 53 PM](https://user-images.githubusercontent.com/77977076/198260143-323986ec-86eb-4b6a-8b6e-b211608fb711.png)

**Comment by shaikamirgh** [comment]
hey, can I do that?

**Comment by asdsyd** [comment]
Alright.

**Comment by asdsyd** [comment]
Dont forget to use 'Closes #issuenumber' to link your PR to this issue.

**Comment by asdsyd** [comment]
This has been assigned to @Shaik-Amir . Please ask before sending a PR.
