### ISSUE TITLE
Home page content design.

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#6]
Open to suggestions.
You can make 3x3 cards that contain titles like mental health, productivity, sleep, food, coffee etc sections
or 
9 vertical colorful columns with clickable titles? 
Something like this below but bigger cards? using tailwind CSS

![Screenshot 2022-10-14 at 9 11 50 PM](https://user-images.githubusercontent.com/77977076/195887019-328bff46-f203-46ef-af1d-1c8398102fd2.png)

**Comment by ishaanbedi** [comment]
Hey! I'd like to work on this!

**Comment by ishaanbedi** [comment]
<img width="1440" alt="Screenshot 2022-10-14 at 10 56 15 PM" src="https://user-images.githubusercontent.com/39641326/195905993-6eee3aba-eefd-40b5-9c85-f15971c67b83.png">
Hey @asdsyd , does this look fine?

**Comment by asdsyd** [comment]
Yup this looks good. Can you add this kind of effect on those cards?

https://user-images.githubusercontent.com/77977076/195909361-fccf2aba-4d85-4f37-a0ce-9d35a7381ee6.mov

src: codeacademy website

**Comment by ishaanbedi** [comment]
> Yup this looks good. Can you add this kind of effect on those cards?

Sure! Working on it.

**Comment by ishaanbedi** [comment]
https://user-images.githubusercontent.com/39641326/195917565-6a97ca11-66a7-4668-98da-121c43a6fb5e.mov

Hey, this was the closest I could get with the current design pattern! Should I initiate a pr?

**Comment by asdsyd** [comment]
That's great! Go ahead.

**Comment by ishaanbedi** [comment]
There's one more doubt, on home page, you've custom CSS for styling, whereas the issue said to use Tailwind CSS, so I've created a separate page called `explore.html` that the "Explore" button on home page redirects to.
Is that okay?

**Comment by asdsyd** [comment]
Yeah that's a good idea. Go ahead.

**Comment by ishaanbedi** [comment]
Hey, I've raised a pr #11 . Please have a look
