### ISSUE TITLE
Organise the repo contents

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#7]
Create folders and organise the files like that used as standard in software development. 
for example:
![Screenshot 2022-10-14 at 9 16 23 PM](https://user-images.githubusercontent.com/77977076/195887726-f9f648bf-e200-4846-8c30-862fba121ef1.png)

**Comment by MRIDUL-MB** [comment]
Hey! I would like to contribute to this. Assign this issue to me.

**Comment by asdsyd** [comment]
Dont forget to include this in your PR 'Closes #IssueNumber' to link PR to this issue.
for eg; 'Closes #99'
