### ISSUE TITLE
Design social media image.

### ISSUE THREAD

**Issue by asdsyd** [asdsyd/Healthy-developer#8]
Social preview
Upload an image to customize your repository’s social media preview.

It should include:
- Healthy Developer title
- Any good logo

The best design would be selected.

Note:
Images should be at least 640×320px (1280×640px for best display).

![repository-open-graph-template](https://user-images.githubusercontent.com/77977076/195890961-bb8ff3c7-7205-48e1-acb2-5bec1c513e90.png)

**Comment by CaraghMcI** [comment]
Hi ! I would like to contribute to this please, could you please assign this to me.

**Comment by CaraghMcI** [comment]
So just to clarify there should be a good logo representing a healthy developer and then the title healthy developer should also be included around the logo.

**Comment by asdsyd** [comment]
Yeah Just like above Github log followed by Github title. 
The bold text in above template can be replaced by "Health and Productivity Tips for Devs" ?
followed by the normal text containing description.

**Comment by 72002sweta** [comment]
if it's open, please assign it to me

**Comment by asdsyd** [comment]
The best design will be picked.

**Comment by 72002sweta** [comment]
I've uploaded the design created a new folder named healthy developer please review it and tell if any change is needed 
thankss,
